### ISSUE TITLE
SciView with NoMachine

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#275]
Testing out SciView-Unstable with NoMachine:

```
This is sciview 0.2.0-beta-6-SNAPSHOT (9c0918ad) ) / scenery 0.7.0-beta-8-SNAPSHOT (4e67655c) ( (9c0918ad)  /  (4e67655c))
Unable to load native library: /tmp/spirvcrossj-natives-tmp6701948663493938205/libspirvcrossj.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/spirvcrossj-natives-tmp6701948663493938205/libspirvcrossj.so)
[WARN] Vulkan unavailable (java.lang.StringIndexOutOfBoundsException: String index out of range: -1, null), Vulkan runtime not installed. Falling back to OpenGL.
Unable to load native library: /tmp/spirvcrossj-natives-tmp5247169081719458975/libspirvcrossj.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/spirvcrossj-natives-tmp5247169081719458975/libspirvcrossj.so)
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:127)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:175)
	at sc.iview.commands.LaunchViewer.run(LaunchViewer.java:68)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:261)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:229)
	at graphics.scenery.backends.Renderer.createRenderer(Renderer.kt)
	at sc.iview.SciView.init(SciView.java:522)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:221)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:494)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:494)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at graphics.scenery.spirvcrossj.Loader.loadNatives(Loader.java:211)
	at graphics.scenery.backends.opengl.OpenGLRenderer.<clinit>(OpenGLRenderer.kt:327)
	... 23 more
```

**Comment by kephale** [comment]
I'm not aware of any demand for NoMachine support at the moment, and my need is now gone.
