### ISSUE TITLE
Using SciView with ImageJ.  Trying to Add Volume (An Image Stack) but get a Java Error

### ISSUE THREAD

**Issue by Hbethray05** [scenerygraphics/sciview#305]
I have tried several times to Add Volume (Image Stack) to SciView using ImageJ (Fiji):
- Started Fiji
- Opened my Image Stack
- Plugins > SciView
- (in SciView) Edit > Add Volume
- I use the voxel size that I collect from Fiji by : Image > Show Info.  This gives me a 1x1x1 voxel size that I put into SciView
- Error is returned in Console (below, starts after *** and ends before ###):
***
[ERROR] Module threw error
java.lang.NoSuchFieldError: list
	at bdv.viewer.BasicViewerState.notifyListeners(BasicViewerState.java:1622)
	at bdv.viewer.BasicViewerState.addSources(BasicViewerState.java:724)
	at bdv.viewer.SynchronizedViewerState.addSources(SynchronizedViewerState.java:496)
	at bdv.viewer.state.ViewerState.<init>(ViewerState.java:81)
	at bdv.viewer.state.ViewerState.<init>(ViewerState.java:69)
	at graphics.scenery.volumes.Volume.<init>(Volume.kt:157)
	at graphics.scenery.volumes.RAIVolume.<init>(RAIVolume.kt:12)
	at sc.iview.SciView.addVolume(SciView.java:1949)
	at sc.iview.SciView.addVolume(SciView.java:2003)
	at sc.iview.SciView.addVolume(SciView.java:1892)
	at sc.iview.SciView.addVolume(SciView.java:1711)
	at sc.iview.commands.demo.VolumeRenderDemo.run(VolumeRenderDemo.java:97)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
###

I get this same error when I try to run a demo and it tries to read an image from:
Read image from sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@25a7058b with 20480 bytes, size=256x20

Any help would be greatly appreciated.  My 3D viewer does not work (I guess due to Java 8) and I would like to be able to work on my lattice in a 3D space.

All the best,
Holly

**Comment by skalarproduktraum** [comment]
Hi Holly, 

sorry for the problem! We are currently working on a new version of sciview, you can grab a development snapshot by disabling the sciview update site, and adding the development update site at `https://sites.imagej.net/SciView-Unstable`. Does that one work for you there?

**Comment by kephale** [comment]
Sincere apologies that this was not properly followed up on. I believe this has been solved for some time. Please let us know if this is still an issue.
