### ISSUE TITLE
Error on a fresh fiji and scivew

### ISSUE THREAD

**Issue by bpavie** [scenerygraphics/sciview#392]
I have just downloaded fij on microsoft windows 10i, updated it, which give me the following installed version of imageJ and java:
ImageJ is version 1.53c
Java 1.8.0_172 64 bit

Then I installed sciview by checking the sciview update site.
![image](https://user-images.githubusercontent.com/1775952/127354334-86996163-4270-49db-a81f-4ee82923c9d7.png)

When I start sciview, I got the following error"

`Started application as PID 8836
This is sciview 0.2.0-beta-9-SNAPSHOT (12709a0d) ) / scenery 0.7.0-beta-8-SNAPSHOT (9747a221) ( (12709a0d)  /  (9747a221))
Resetting language to Python
Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
[ERROR] Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
[ERROR] Could not instantiate renderer. Is your graphics card working properly and do you have the most recent drivers installed?
java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:3868)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:508)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:205)
	at sc.iview.SciView.init(SciView.kt:382)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:217)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:491)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:491)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:127)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:175)
	at sc.iview.ActiveSciViewPreprocessor.getValue(ActiveSciViewPreprocessor.java:64)
	at sc.iview.ActiveSciViewPreprocessor.getValue(ActiveSciViewPreprocessor.java:48)
	at net.imagej.display.process.SingleInputPreprocessor.process(SingleInputPreprocessor.java:83)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:3868)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:508)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:205)
	at sc.iview.SciView.init(SciView.kt:382)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:217)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:491)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:491)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
[INFO] Reading available sites from https://imagej.net/
`

I am running it on a laptop on Windows 10 with the NVIDIA card Quadro RTX 3000 with the driver version 465.89 (only one graphic card)

Best,
Benjamin

**Comment by skalarproduktraum** [comment]
Hey Benjamin!  

We have changed our update site schemes a bit such that we can provide updates for different development lines. The process is documented here: https://docs.scenery.graphics/sciview/installation/installing-the-development-sciview-plugin-for-fiji -- and the name of the latest update site is `sciview-buttercup`. Could you please remove the regular `SciView` update site, and add `sciview-buttercup` and see if that resolves the issue?

**Comment by skalarproduktraum** [comment]
Hey again!

I have now added the link I posted above to the README on the Github repo, so things should be clearer for the next one to try 👍  I have also added the UI overview image to the README, so people know what user interface to expect.

**Comment by skalarproduktraum** [comment]
Hey @bpavie! I was just wondering if you've been able to get it working with the current update site. Please let me know if you need any help 👍 You're of course also welcome to join our chat at gitter.im/scenerygraphics/sciview, should you have any further questions 😎

**Comment by bpavie** [comment]
Hi @skalarproduktraum 

Sorry for the late answer, I disable the sciview repository and added an selected the sciview-buttercup one,
![image](https://user-images.githubusercontent.com/1775952/129567594-fd74162d-8dc9-4a52-b7af-0d50bf871847.png)
and restarted Fiji.
Then to test, I opened the sample T1-head (16-bits), then started sciview but still get an error in the console window:

```
Started application as PID 9456
This is sciview / scenery, development version ( /  (9877ce))
Resetting language to Python
Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
Creating Vulkan instance with extensions VK_KHR_win32_surface,VK_KHR_surface and layers 
[ERROR] Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
[ERROR] Could not instantiate renderer. Is your graphics card working properly and do you have the most recent drivers installed?
java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:2429)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:497)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:217)
	at sc.iview.SciView.init(SciView.kt:384)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:226)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:504)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:504)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:127)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:175)
	at sc.iview.commands.LaunchViewer.run(LaunchViewer.kt:60)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:2429)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:497)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:217)
	at sc.iview.SciView.init(SciView.kt:384)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:226)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:504)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:504)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
```

After that, I can close sciview (which display nothing) and the console window but Fiji main window and the image are not possible to close.
