### ISSUE TITLE
VolumeTimeseriesDemo is broken

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#510]
When I run VolumeTimeseriesDemo no nodes are added to the scene, and BDV is empty.

**Comment by kephale** [comment]
The exception is being gobbled by the current SciJava bug, but I was able to get this when just testing the dataset itself.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void bdv.tools.InitializeViewerState.initTransform(bdv.viewer.ViewerPanel)'
	at bdv.util.BdvHandle.tryInitTransform(BdvHandle.java:222)
	at bdv.util.BdvHandle.add(BdvHandle.java:207)
	at bdv.util.BdvFunctions.addRandomAccessibleInterval(BdvFunctions.java:541)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:114)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:89)
	at sc.iview.commands.demo.animation.VolumeTimeseriesDemo$Companion.main(VolumeTimeseriesDemo.kt:147)
	at sc.iview.commands.demo.animation.VolumeTimeseriesDemo.main(VolumeTimeseriesDemo.kt)
```

**Comment by moreApi** [comment]
<img width="852" alt="image" src="https://github.com/scenerygraphics/sciview/assets/10872331/974a1275-9a50-4a0c-84bf-4a8bf4b3c0f1">
For me there is something in BDV but it is far in the corner. But SciView is empty for me also.

**Comment by kephale** [comment]
Oh good eyes! 

This exception is concerning though.

**Comment by kephale** [comment]
This works with updated BDV dependencies. Confirmed working with:

```
    implementation("sc.fiji:bigdataviewer-core:10.4.7")
    implementation("sc.fiji:bigdataviewer-vistools:1.0.0-beta-32")
```
