### ISSUE TITLE
TextDemo is broken

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#514]
I'm getting

```
java.lang.NullPointerException: Parameter specified as non-null is null: method sc.iview.SciView.addMesh, parameter mesh
	at sc.iview.SciView.addMesh(SciView.kt)
	at sc.iview.commands.demo.basic.TextDemo.run(TextDemo.java:88)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kephale** [comment]
Oops, but solved by this accidental push to main https://github.com/scenerygraphics/sciview/commit/93e27663aa55c83584de983e7f5bd619ddc1b816
