### ISSUE TITLE
Adding objects to the scene breaks for some object types

### ISSUE THREAD

**Issue by smlpt** [scenerygraphics/sciview#565]
Several entries from the `Add` menu won't add objects to the scene, but instead show a warning message.
These include:
- [x] Compass:
```The module "sc.iview.commands.add.AddOrientationCompass" is invalid:
  Invalid final parameter: private final float
  sc.iview.commands.add.AddOrientationCompass.axisLength
  Invalid final parameter: private final float
  sc.iview.commands.add.AddOrientationCompass.AXESBARRADlUS
  Invalid final parameter: private final org.joml.Vector3f
  sc.iview.commands.add.AddOrientationCompass.xColor
  Invalid final parameter: private final org.joml.Vector3f
  sc.iview.commands.add.AddOrientationCompass.yColor
  Invalid final parameter: private final
  sc.iview.commands.add.AddOrientationCompass.zColor
 ```
- [ ] Label Image:
```
`currentImage` is required but unset.
```
- [x] Point Light:
```
The module "sc.iview.commands.add.AddPointLight" is invalid:
- Invalid final parameter: private final sc.iview.SciView
sc.iview.commands.add.AddPointLight.sciView
```
- [ ] Protein from file:
```
`files` is required but unset.
```
- [ ] Volume from ImageJ:
```
`image` is required but unset.
```

**Comment by kephale** [comment]
Add Proteins from File does not throw that error for me, but when I do add the PDBs to list and try to open them I get:

```
[ERROR] Command errored: Protein from files ...
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.biojava.nbio.structure.io.PDBFileParser.pdb_CRYST1_Handler(PDBFileParser.java:1543)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2694)
	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2580)
	at org.biojava.nbio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:140)
	at org.biojava.nbio.structure.io.LocalPDBDirectory.getStructure(LocalPDBDirectory.java:323)
	at org.biojava.nbio.structure.URLIdentifier.loadStructure(URLIdentifier.java:168)
	at org.biojava.nbio.structure.align.client.StructureName.loadStructure(StructureName.java:517)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:503)
	at org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:487)
	at org.biojava.nbio.structure.StructureIO.getStructure(StructureIO.java:97)
	at graphics.scenery.proteins.Protein$MyProtein.fromID(Protein.kt:29)
	at sc.iview.commands.add.AddProteinFromFiles.run(AddProteinFromFiles.kt:66)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 20 more
```

@skalarproduktraum the stack trace on this runs through scenery and the error looks like a missing dependency?

**Comment by kephale** [comment]
For Volume from ImageJ I get:

<img width="931" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/31374d8b-b37c-4b98-a194-8cfbbaebb21a">

even through the T1 head sample is already open.

**Comment by kephale** [comment]
I noticed this UI issue with Add Proteins from Files:

<img width="592" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/cbcd009d-6ad2-4ca0-ac9a-0143fb97764f">

but it should show these extensions: pdb/mmtf/cif

**Comment by kephale** [comment]
The remaining issues are:

- harvesting input `Dataset` isn't working
- `javax/xml/bind/JAXBException` when opening pdbs from file
